[package]
name = "p02_senjen"
version = "0.1.0"
edition = "2021"

[dependencies]
xml-rs = "0.8.21"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
regex = "1.10.6"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
clap = { version = "4.5.16", features = ["derive"] }
